spring:
  application:
    name: greeting-ms
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-ms:
    greeting: "Hola"
    default-value: "Mundo"